Repository Shariar-Hasan/QuoteVerse, pull requests merged in 2023-10, with the labels that each got.

#7 Modified Background and add dynamic backgournd button
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#8 adding some styles and updates
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#10 added new quotes
  Quotes.js
Labels: hacktoberfest-accepted, hacktoberfest

#11 Add new quotes
  Quotes.js
Labels: hacktoberfest-accepted

#16 [Added] Added 10 new quotes
  Quotes.js
Labels: hacktoberfest-accepted, hacktoberfest

#17 Added new quote
  Quotes.js
Labels: hacktoberfest-accepted, hacktoberfest

#19 Added new quote
  Quotes.js
Labels: hacktoberfest-accepted, hacktoberfest

#20 Added the Contributors page
  Contributors/contributors.html
  Contributors/script.js
  Contributors/styles.css
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#25 feat: Button change #23
  assets/css/style.css
  index.html
  source/partials/_variables.scss
Labels: hacktoberfest-accepted, hacktoberfest

#31 Adding Quotes
  Quotes.js
Labels: hacktoberfest-accepted, hacktoberfest

#30 Added the facebook share button link
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#35 feat: back button on contributors page
  Contributors/contributors.html
  Contributors/styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#57 Feat: Copy to Clipboard
  assets/css/style.css
  assets/js/main.js
  index.html
Labels: hacktoberfest-accepted, hacktoberfest, feature

#65 feat: adding 3 motivational, and 3 programming quotes
  Quotes.js
Labels: hacktoberfest-accepted, hacktoberfest

#104 feat: Hover effects and commit count in contributors-card
  Contributors/contributors.html
  Contributors/script.js
  Contributors/styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#114 added 5 new quotes to Quotes.js
  Quotes.js
Labels: hacktoberfest-accepted, hacktoberfest

#141 feat: add download image option
  assets/js/main.js
  index.html
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#153 Duplicates Removed
  Duplicates.txt
  Quotes.js
Labels: hacktoberfest-accepted, hacktoberfest

#156 feat: adding quotes of motivational and philosophical category
  Quotes.js
Labels: hacktoberfest-accepted, hacktoberfest
